name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: src
          CLEAN: true
